### ISSUE TITLE
Problem with v3.0.0 package on npm (styles not loading correctly)

### ISSUE THREAD

**Issue by kfrederix** [fil0157/angular-colorful#1]
Hi there,

First of all: thank you for porting this to angular and maintaining it! It's a really nice and lightweight component.

However, there seems to be an issue with the v3.0.0 package on npm. When you install it and run, nothing is shown in the output because the styles are not loading correctly.

When I clone this repo, build the lib myself and then copy the output to the node_modules folder of my other project, then it works fine!

You can also re-produce this on the demo app in this repo: just remove `angular-colorful` from `paths` in `tsconfig.json` and install it with `npm i angular-colorful`: you should notice that the colorpicker is not visible anymore in the demo.

Could you please have a look at this and maybe publish again to npm?

**Comment by Kyoss79** [comment]
I got the same issue, the components are not showing...

**Comment by fil0157** [comment]
Hi all!

I apologize for such a long response. I finally found time for this library and fixed everything, as well as updated to the latest version of Angular and made some improvements.
